# Generated by Django 6.0.2 on 2026-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='изображение'),
        ),
    ]
